### ISSUE TITLE
Consider minimal Java version

### ISSUE THREAD

**Issue by keilw** [JavaMoney/jsr354-ri-bp#1]
Looking at ideas for Android support like https://github.com/JavaMoney/javamoney-shelter/issues/17 we should ensure, the BPs also work there. API even Java ME Embedded 8, too (which is largely compatible with Java SE 7 anyway)

**Comment by keilw** [comment]
The somewhat "inspirational" ThreeTen BP also claims "Backport of functionality based on JSR-310 to Java SE 6 and 7. This is NOT an implementation of JSR-310." so Java SE 6 (compatible wiith pretty much every Android version still relevant) might be a good idea for this BP, too.

**Comment by atsticks** [comment]
Yep, I am as well targeting Java 6... removed all the nice diamonds ;(

2015-03-11 20:55 GMT+01:00 Werner Keil <notifications@github.com>:

> The somewhat "inspirational" ThreeTen BP also claims "Backport of
> functionality based on JSR-310 to Java SE 6 and 7. This is NOT an
> implementation of JSR-310." so Java SE 6 (compatible wiith pretty much
> every Android version still relevant) might be a good idea for this BP, too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JavaMoney/jsr354-ri-bp/issues/1#issuecomment-78357576>
> .
>



-- 
*Anatole Tresch*
Java Engineer & Architect, JSR Spec Lead
Glärnischweg 10
CH - 8620 Wetzikon

*Switzerland, Europe Zurich, GMT+1*
*Twitter:  @atsticks*
*Blogs: **http://javaremarkables.blogspot.ch/
<http://javaremarkables.blogspot.ch/>*

*Google: atsticksMobile  +41-76 344 62 79*

**Comment by keilw** [comment]
Then if that's the case, the artifactId should not be misleading like "java7" ;-)

**Comment by atsticks** [comment]
AFAIK the API is also compatible with Java 6. But the RI also has lots of references to Objects. I do not have time to remove them, so we will stick on Java 7 I think.

**Comment by keilw** [comment]
Then in the API maybe the artifactId should say "prejava8" or "java6" (not a lot of real use cases are likely to still use JDK5) while the RI may say "java7". Otherwise it sounds like the minimal version which is not correct. Or stick to "bp" like in the Repo name?;-)

**Comment by atsticks** [comment]
bp ;)

2015-03-20 15:39 GMT+01:00 Werner Keil <notifications@github.com>:

> Then in the API maybe the artifactId should say "prejava8" or "java6" (not
> a lot of real use cases are likely to still use JDK5) while the RI may say
> "java7". Otherwise it sounds like the minimal version which is not correct.
> Or stick to "bp" like in the Repo name?;-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JavaMoney/javamoney-moneta-bp/issues/1#issuecomment-84033731>
> .
>



-- 
*Anatole Tresch*
Java Engineer & Architect, JSR Spec Lead
Glärnischweg 10
CH - 8620 Wetzikon

*Switzerland, Europe Zurich, GMT+1*
*Twitter:  @atsticks*
*Blogs: **http://javaremarkables.blogspot.ch/
<http://javaremarkables.blogspot.ch/>*

*Google: atsticksMobile  +41-76 344 62 79*
