### ISSUE TITLE
Currency symbol assumption is wrong

### ISSUE THREAD

**Issue by keilw** [JavaMoney/jsr354-ri-bp#29]
See https://github.com/JavaMoney/jsr354-ri/issues/149

**Comment by keilw** [comment]
@atsticks If the RI fixed this, it should also be fixed in the BP otherwise we risk different behavior which is not acceptable till the BP could be retired (AFAIK this can only be done after a new JSR or different kind of project along the lines of Jakarta EE was found)

**Comment by atsticks** [comment]
It has been fixed in bp as well.
