### ISSUE TITLE
Thousand separator (space) not working when parsing

### ISSUE THREAD

**Issue by orousseil** [JavaMoney/jsr354-ri-bp#46]
Hello
The french thousand separator is the space character. When you parse a money amount with currency from a string it doesn't work !!

See this test case for example :

    @Test
    public void testParseKO() {
        MonetaryAmountFormat format = MonetaryFormats
                .getAmountFormat(AmountFormatQueryBuilder.of(Locale.FRANCE)
                        .set(CurrencyStyle.CODE)
                        .build());
        MonetaryAmount amountOk = format.parse("123,01 EUR");
        MonetaryAmount amountKo = format.parse("14 000,12 EUR");
        assertThat(amountOk.getNumber().doubleValueExact()).isEqualTo(123.01); // OK
        assertThat(amountKo.getNumber().doubleValueExact()).isEqualTo(14000.12); // KO
    }

**Comment by keilw** [comment]
Hi, thanks for bringing that up. Are you able to cross-check with the Java 8+ RI Moneta, if the same problem occurs there as well? It should be patched, but it's good to know, if it only affects one RI or both.

**Comment by orousseil** [comment]
Sorry, i've post in the wrong project. I have originally detect this bug in the java 8+ implementation. So I don't know if the problem is the same for java 7 but it should. I will recreate an issue for the java 8+ github project

**Comment by thodorisbais** [comment]
Are we sure this is still the case after a year? I am not familiar enough with JSR-354, but this is what I'm getting when I run the fore-mentioned example against the latest HEAD:

`javax.money.format.MonetaryParseException: Unparseable number: "123,01"`

I haven't checked the codebase / debugged it thoroughly, but before going there, I wanted to check whether this is still the case or something change. 

@orousseil could you please help me here? Does this issue still occur when you run your fore-mentioned case against the latest HEAD? Does it pass? Do you get the error I got or you only get an error? for the second/spacing case?

Or maybe I need to configure something in my IntelliJ for this particular case to fake the FR locale? I think configuring it programmatically in the test itself should be enough.

**Comment by keilw** [comment]
Please have a look at https://github.com/JavaMoney/jsr354-ri-bp/blob/master/src/test/java/org/javamoney/moneta/format/MonetaryFormatsTest.java. It seems that French locale might be treated properly now, check in detail in the test class, but there is nothing ignored at least not for this one. What's definitely open is #55.

**Comment by keilw** [comment]
@atsticks, @otaviojava IMO this really must be fixed, there are other minor things that the BP could neglect, but the two showstoppers including this one (which was fixed in the Java 8 RI) should be resolved before we are ready for MR1.

**Comment by keilw** [comment]
@thodorisbais if you try to parse "123,01" without a particular locale e.g. Germany or (is it the same there?) Netherlands, it is the right behavior, the default is English.

**Comment by thodorisbais** [comment]
I need to check that, Werner. Hope I can make some time during the weekend.
