### ISSUE TITLE
Error loading javamoney.properties, ignoring jar:file

### ISSUE THREAD

**Issue by MALPI** [JavaMoney/jsr354-ri-bp#58]
When adding `org.javamoney:moneta:1.3` to the classpath I get the following error on start:

```
SEVERE: Error loading javamoney.properties, ignoring jar:file:~/.m2/repository/org/javamoney/moneta-bp/1.1/moneta-bp-1.1.jar!/javamoney.properties
java.lang.IllegalStateException: AmbiguousConfiguration detected for 'load.ECBHistoricRateProvider.resource'.
```

Running with Java 1.8.

**Comment by keilw** [comment]
It looks like this only happens when moneta and moneta-bp are both on the same classpath, something that should not happen in most cases, we may not fix this.
