### ISSUE TITLE
CurrencyConversionException 

### ISSUE THREAD

**Issue by dhavalkarnatki** [JavaMoney/jsr354-ri-bp#59]
MonetaryAmount oneDollar = Monetary.getDefaultAmountFactory().setCurrency("USD")
			      .setNumber(1).create();

			    CurrencyConversion conversionEUR = MonetaryConversions.getConversion("EUR");

			    MonetaryAmount convertedAmountUSDtoEUR = oneDollar.with(conversionEUR);

**Comment by keilw** [comment]
@dhavalkarnatki thanks for raising this, please try to use the Java 8+ RI as Java 7 or earlier are EOL for a long time now and the baseline for this JSR is the LTS Java 8.
